### ISSUE TITLE
Move G2IniParams.py from SDK to g2/python

### ISSUE THREAD

**Issue by docktermj** [Senzing/g2search#17]
With the [Move G2IniParams.py from SDK to g2/python](https://github.com/Senzing/g2-python/issues/141), G2Search.py needs to import G2IniParams differently

https://github.com/Senzing/g2search/blob/94571d67f31b0db2e6722629c6d5c949b9de554e/G2Search.py#L23

Dependencies:

- https://github.com/Senzing/g2-python/issues/141

**Comment by jbutcher21** [comment]
This must have already been taken care of.
